### ISSUE TITLE
Using WithEnvironment after dapr doesn't work

### ISSUE THREAD

**Issue by bit365** [dotnet/aspire#1553]
I need to reference an environment variable in Dapr's component configuration file, but after using the following code, I cannot get the variable in the dapr sidecar.

```csharp
var apiServiceSidecar = builder.AddProject<Projects.AspireApp_ApiService>("apiservice")
    .WithDaprSidecar(new DaprSidecarOptions
    {
        AppId = "apiservice",
        DaprGrpcPort = 50001,
        DaprHttpPort = 3500,
        ResourcesPaths = ["./components"],
    }).WithEnvironment("testtesttesttesttesttesttest", "testvalue");
```

For example, the secretstores.local.env component in dapr obtains values ​​from environment variables.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: env-secret-store
spec:
  type: secretstores.local.env
  version: v1
```
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mqtt-pubsub
spec:
  type: pubsub.mqtt3
  version: v1
  metadata:
    - name: url
      secretKeyRef:
        name: testtesttesttesttesttesttest
auth:
  secretStore: env-secret-store
```

Unable to extract value from testtesttesttesttesttesttest
