### ISSUE TITLE
builder.AddDaprStateStore error - Dapr is not detecting `actorStateStore` setting

### ISSUE THREAD

**Issue by ScottArbeit** [dotnet/aspire#3039]
Hi! I could use another set of eyes on this... I'm converting a Dapr project from Kubernetes to Aspire, and I'm getting `Have you set the - name: actorStateStore value: \"true\" in your state store component file?`, when, indeed, I have.

## AppHost\Program.cs

The relevant bits from `AppHost\Program.cs` are:

``` csharp
builder.AddDapr(options =>
{
    options.DaprPath = config["DAPR_PATH"];
    options.EnableTelemetry = true;
});

// Add secret store
var secretstore = builder.AddDaprComponent("secretstore", "secretstores.azure.keyvault",
    new DaprComponentOptions { LocalPath = Path.Combine(daprConfigurationPath(), "secretstore - local.yaml") });

// Add actor state store
var actorstorage = builder.AddDaprStateStore("actorstorage",
    new DaprComponentOptions { LocalPath = Path.Combine(daprConfigurationPath(), "actorstorage - local.yaml") });

// Add pub/sub
var graceeventstream = builder.AddDaprPubSub("graceeventstream",
    new DaprComponentOptions { LocalPath = Path.Combine(daprConfigurationPath(), "graceeventstream - local.yaml") });

// etc.

// Add my .NET project
var graceServer = builder.AddProject<Projects.Grace_Server>("grace-server")
    .WithDaprSidecar(new DaprSidecarOptions { ... }) + lots of .WithEnvironment()

builder.Build().Run();
```

## Dapr configuration
I'm configuring the state store with `actorstorage - local.yaml`, which is identical to what I configure Kubernetes with. I do set `actorStateStore` in it:

``` yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actorstorage
spec:
  type: state.azure.cosmosdb
  version: v1
  initTimeout: 1m
  metadata:
  - name: actorStateStore    <---- it's right here
    value: "true"            <---- i'm not crazy,  right?
  - name: url
    secretKeyRef:
      name: azurecosmosdburl
      key: azurecosmosdburl
  - name: masterKey
    secretKeyRef:
      name: azurecosmosdbkey
      key: azurecosmosdbkey
  - name: database
    secretKeyRef:
      name: cosmosdatabasename
      key: cosmosdatabasename
  - name: collection
    secretKeyRef:
      name: cosmoscontainername
      key: cosmoscontainername
auth:
  secretStore: secretstore
```

## Dapr starts correctly
The log looks good:

```
time="2024-03-19T23:29:24.3114502-07:00" level=debug msg="Found component: actorstorage (state.azure.cosmosdb/v1)" app_id=grace-server instance=Workstation scope=dapr.runtime type=log ver=1.13.0
time="2024-03-19T23:29:24.3124999-07:00" level=debug msg="Loading component: actorstorage (state.azure.cosmosdb/v1)" app_id=grace-server instance=Workstation scope=dapr.runtime.processor type=log ver=1.13.0
time="2024-03-19T23:29:25.3526777-07:00" level=debug msg="CosmosDB init start" app_id=grace-server component="actorstorage (state.azure.cosmosdb/v1)" instance=Workstation scope=dapr.contrib type=log ver=1.13.0
time="2024-03-19T23:29:25.5904111-07:00" level=info msg="Component loaded: actorstorage (state.azure.cosmosdb/v1)" app_id=grace-server instance=Workstation scope=dapr.runtime.processor type=log ver=1.13.0
...
time="2024-03-19T23:29:27.442645-07:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 3174ms" app_id=grace-server instance=Workstation scope=dapr.runtime type=log ver=1.13.0
```

## Sad trombone
Unfortunately, when I test my code, I get `Have you set the - name: actorStateStore value: \"true\" in your state store component file?"` from Dapr:

```
level=debug msg="api error: code = Internal desc = the state store is not configured to use the actor runtime. Have you set the - name: actorStateStore value: \"true\" in your state store component file?" app_id=grace-server instance=Workstation scope=dapr.runtime.http type=log ver=1.13.0
```

So...

Is there anything in Aspire's Dapr support that could be causing this?
