### ISSUE TITLE
Usernames and passwords in connection strings need to be escaped

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#3117]
While investigating #2247 I used a parameter to create a stable password for a RabbitMQ resource, only to find that the password I'd generated contained a character that broke the connection string. RabbitMQ connection strings are actually URIs, so if the username or password contains restricted characters (e.g. `@`) then the RabbitMQ client fails due to the URI being invalid.

I updated `ReferenceExpression` to support custom value escaping and a convenience method for getting a URI escaped version of an existing `ReferenceExpression` and that solves the issue for runtime, but this issue will occur during manifest processing too. Resolving that is a much bigger challenge that will need some thought.

**Comment by eerhardt** [comment]
I think in order to be able to solve this generically, and in all the places we need to fix it, we will need to:

1. Have a set of "well known" escape strategies/algorithms.
2. Encode which escape strategy to use inside the `ReferenceExpression`, so it gets written to the manifest.

RabbitMQ uses URIs, but PostgreSQL uses DbConnectionString. To properly escape any string in a DbConnectionString, we would need to add single quotes `'` around the value, and then escape any real single quotes in the value by doubling them: `''`.

So at a minimum we would need 2 strategies: URI escaping and single-quote escaping.

As you pointed out above, we would need to put this in the manifest and have any deployment tools (like `azd`) understand these strategies.

cc @davidfowl @mitchdenny @ellismg @vhvb1989

**Comment by DamianEdwards** [comment]
So we'd represent this in the manifest something like this?
`"amqp://{urlencode(resources.rabbitusr.value)}:{urlencode(resources.rabbitpw.value)}@{resources.rabbitmq.bindings.tcp.host}:{resources.rabbitmq.bindings.tcp.port}"`

**Comment by eerhardt** [comment]
> So we'd represent this in the manifest something like this? `"amqp://{urlencode(resources.rabbitusr.value)}:{urlencode(resources.rabbitpw.value)}@{resources.rabbitmq.bindings.tcp.host}:{resources.rabbitmq.bindings.tcp.port}"`

Yep - something like that is what I was thinking.

**Comment by DamianEdwards** [comment]
@davidfowl we thinking punt this until post-GA now? Or do we think this will be common enough when considering values in URIs and connection strings that we need to mitigate it earlier?

**Comment by davidfowl** [comment]
yes I think we can do something specifically for URLs and connection strings in azd without putting functions in the manifest (work needs to happen in azd anyways). I’m thinking for now, they can detect a url and do this magic encoding.

**Comment by DamianEdwards** [comment]
So you're thinking we have AZD recognize URIs and encode themselves for GA?

**Comment by eerhardt** [comment]
> we have AZD recognize URIs and encode themselves for GA?

And connection strings.  (at least that's what I understand from the above)

**Comment by davidfowl** [comment]
> So you're thinking we have AZD recognize URIs and encode themselves for GA?

Yes, that's how we address this for GA.

> And connection strings. (at least that's what I understand from the above)

Yes

**Comment by DamianEdwards** [comment]
OK I've put in preview.6 and opened https://github.com/Azure/azure-dev/issues/3598

**Comment by oskardudycz** [comment]
@DamianEdwards I think that Postgres containers have a similar issue.

**Comment by mitchdenny** [comment]
Now that we are past GA ... how do we want to handle this?

**Comment by joperezr** [comment]
@DamianEdwards is this something we want to fix for 8.1?

**Comment by DamianEdwards** [comment]
@joperezr if we have a ready-to-go plan to fix it at both runtime and deployment time (i.e. in AZD and Aspir8) otherwise I'd move it out.

**Comment by davidfowl** [comment]
This is a really hard problem to solve generally. Today aspire has [a model](https://gist.github.com/davidfowl/b408af870d4b5b54a28bf18bffa127e1) represented with C# code and resources may translate that model into something like a manifest (what is used today for azd and aspirate), docker compose file, or bicep, or cloud formation etc. 

The current assumption is that values (see the value references in the doc) are lazy and translate into external parameters when doing the translation. As an example, if you need to translate an aspire parameter to bicep there's a mapping stored to understand how the model in C# maps to bicep parameters and the runtime can fill those in when executing.

When publishing it's more difficult. Take this example:

Lowercase the input parameter.

```C#
var builder = DistributedApplication.CreateBuilder(args);

var param = builder.AddParameter("param1");
var project = builder.AddProject<Projects.Api>("project1")
                     .WithEnvironment("ParamLower", param.Resource.Value.ToLowerInvariant());

builder.Build().Run();
```

This looks simple, but it assumes you can do this all in C#. This may work in run mode, and you'll be able to see the transformation on the input parameter in the "ParamLower" environment variable at runtime. When we translate this into the manifest or any other publishing target, we don't have the value, nor can we lowercase it, we need to store that somewhere.

I see some ways forward here:
- Support a fixed set of transformations. At a minimum make it possible to express the transformation in an inspectable way (there are multiple ways to do this).
- Do "client side evaluation" this requires a runtime before launching various deployment engines/runtimes parameter filling.

**Comment by sebastienros** [comment]
@John-Leitch we have added the possibility of encoding values, and we would like to apply these changes to the manifest now (we have updated the generated bicep already).

The previous suggestion was to use a format like this

```
"amqp://{urlencode(resources.rabbitusr.value)}:{urlencode(resources.rabbitpw.value)}@{resources.rabbitmq.bindings.tcp.host}:{resources.rabbitmq.bindings.tcp.port}"
```

Is that something that would be possible to handle on your side?
In order to prevent any disruption, we could add an argument to the publisher command to no emit these.

@vhvb1989 is also looking at how AZD could handle this new information.

Right now we only handle url encoding, but we may want to define a few others that are ubiquitous like connection string escaping (`=` and `;`), toLower, toUpper, ...? Using a method-like syntax could also open for standard things like substring, replace (which are available in Bicep too) but that might be too ambitious.

**Comment by sebastienros** [comment]
@vhvb1989 came up with a nicer solution that would be like this:

```yaml
"cache-password": {
      "type": "parameter.v0",
      "value": "{cache-password.inputs.value}",
      "inputs": {
        "value": {
          "type": "string",
          "secret": true,
          "default": {
            "generate": {
              "minLength": 22,
              "special": false
            }
          }
        }
      }
    },
"cache-password-encoded": {
      "type": "annotated.string",
      "value": "{cache-password.value}",
      "filter": "url"
    },
"api": {
      "type": "project.v0",
      "path": "../../AzureContainerApps.ApiService/AzureContainerApps.ApiService.csproj",
      "env": {
        "CACHE_PASSWORD": "{cache-password.value}",
        "CACHE_URI": "redis://:{cache-password-encoded.value}@{cache.bindings.tcp.host}:{cache.bindings.tcp.port}",
      },
      "bindings": {
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "external": true
        },
        "https": {
          "scheme": "https",
          "protocol": "tcp",
          "transport": "http",
          "external": true
        }
      }
    },

```

I used `"filter": "url"` but this could be a more complex object if we intend to support arguments.
