### ISSUE TITLE
[Azure Storage] Add an option to have it run Azurite in a container when working locally

### ISSUE THREAD

**Issue by hades200082** [dotnet/aspire#3805]
With my current Docker Compose setup I use the Azurite docker image to run storage locally during development using the following service definition in the compose yaml file.

```yaml
azurite:
  image: "mcr.microsoft.com/azure-storage/azurite"
  restart: unless-stopped
  ports:
    - "10000-10002:10000-10002"
  networks:
    customnet:
      ipv4_address: 192.168.55.30
  volumes:
    - azurite-volume:/data
```

To further aid Aspire's goal of making local development easier for containerised applications it would be great if there could be an option to use Azurite when running locally.

Something similar to the `RunAsEmulator()` option available on Cosmos DB.
