### ISSUE TITLE
dapr sidecar fails to start up when component uses azure storagequeues

### ISSUE THREAD

**Issue by OptimusPi** [dotnet/aspire#6418]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When using Aspire + dapr sidecar (to only publish a message to) **Azure Storage Queues**, the dapr sidecar will fail to start up in local development unless the secret key is supplied. 

output of `dotnet list user-secrets --id my-example-api` is:
![Image](https://github.com/user-attachments/assets/bb72b684-861e-4950-9793-77d46155d0b2)

AppHost Program.cs:

```cs
using Microsoft.Extensions.Configuration;

var builder = DistributedApplication.CreateBuilder(args);

builder.Configuration.AddUserSecrets("my-example-api");

builder.AddDapr();

// Add API
var apiServer = builder
    .AddProject<Projects.My_Example_API>("my-example-api")
    .WithDaprSidecar(options: new ()
    {
        AppId = "c2c-exchange-api-dapr",
        ResourcesPaths = [ "../../components" ]
    })

```

dapr sidecar component:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: report-builder
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: accountName
    secretKeyRef:
      name: storageAccount
  - name: queueName
    value: report-builder
auth:
  secretStore: localsecrets
```

secretstore.file.yml:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecrets
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ../../.env/localsecrets.json # Path relative to the AppHost
  - name: nestedSeparator
    value: "__"
```

Error:

```
2024-10-21T08:54:59 time="2024-10-21T08:54:59.0318697-05:00" level=info msg="Closing HTTP server [::]:53766…" app_id=my-example-api-dapr instance=pifreak-asus-rog scope=dapr.runtime.http type=log ver=1.14.4
2024-10-21T08:54:59 time="2024-10-21T08:54:59.0318697-05:00" level=info msg="stopping mDNS server for app id: my-example-api-dapr" app_id=my-example-api-dapr component="nr (mdns/v1)" instance=pifreak-asus-rog scope=dapr.contrib type=log ver=1.14.4
2024-10-21T08:54:59 time="2024-10-21T08:54:59.0338804-05:00" **level=fatal msg="Fatal error from runtime: process component report-builder error: [INIT_COMPONENT_FAILURE]: initialization error occurred for report-builder (bindings.azure.storagequeues/v1): init timeout for component report-builder (bindings.azure.storagequeues/v1) exceeded after 5s"** app_id=my-example-api-dapr instance=pifreak-asus-rog scope=dapr.runtime type=log ver=1.14.4
2024-10-21T08:54:59
 The daprd process exited with error code: exit status 1
2024-10-21T08:55:08
 Error exiting Dapr: exit status 1
2024-10-21T08:55:08 Could not update sidecar metadata for cliPID: PUT http://127.0.0.1:53766/v1.0/metadata/cliPID giving up after 5 attempt(s): Put "http://127.0.0.1:53766/v1.0/metadata/cliPID";: dial tcp 127.0.0.1:53766: connectex: No connection could be made because the target machine actively refused it.
2024-10-21T08:55:08 You're up and running! Dapr logs will appear here.
2024-10-21T08:55:08 
2024-10-21T08:55:08 
2024-10-21T08:55:08 terminated signal received: shutting down
```

**Workaround (not ideal because maybe some devs don't have access to the secret key)**

Setting the storage account secret key in the secrets store component for dapr makes it work:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: report-builder
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: accountKey
    value: "ABCDEF1234567890=="
  - name: accountName
    secretKeyRef:
      name: storageAccount
  - name: queueName
    value: report-builder
auth:
  secretStore: localsecrets
```

### Expected Behavior

in local development dapr sidecar should run successfully, and allow the API to publish messages to the queue without requiring the secret account key.

### .NET Version info

```
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.58db758f
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.403\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.2.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.1\WorkloadManifest.json   
   Install Type:              Msi


Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  2.2.109 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.135 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  8.0.110 [C:\Program Files\dotnet\sdk]
  8.0.206 [C:\Program Files\dotnet\sdk]
  8.0.306 [C:\Program Files\dotnet\sdk]
  8.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
