### ISSUE TITLE
Add support for --scheduler-host-address argument to Dapr sidecar

### ISSUE THREAD

**Issue by mfcollins3** [dotnet/aspire#6477]
Dapr has two runtime services that it uses: the [placement service](https://docs.dapr.io/concepts/dapr-services/placement/) and the [scheduler service](https://docs.dapr.io/concepts/dapr-services/scheduler/). By default, Dapr sidecars will look for these services accessible on `localhost` and running locally within Docker Desktop. When deployed in self-hosted mode through Docker Compose or another solution, these services could be located at other network addresses. For example, in one of my current projects, I am using a development container to build my solution and have a `compose.yaml` file like this:

```yaml
services:
  app:
    image: mcr.microsoft.com/devcontainers/base:1.0.17-bookworm
    ports:
      - "49000:49000"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - placement
    # Required for ptrace-based debuggers like C++, Go, and Rust.
    # See https://code.visualstudio.com/docs/devcontainers/create-dev-container#_use-docker-compose
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  placement:
    image: daprio/dapr:1.14.4
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"

  scheduler:
    image: daprio/dapr:1.14.4
    command: ["./scheduler", "--port", "50007"]
    ports:
      - "50007:50007"
    volumes:
      - type: tmpfs
        target: /data
```

In this case, when I run my Dapr service (or just the sidecar when debugging) from the development container, I need to specify both the `--placement-host-address` and `--scheduler-host-address` arguments:

```bash
dapr run --app-id authorization-service \
  --app-protocol grpc \
  --config .dapr/config.yaml \
  --dapr-grpc-port 55000 \
  --placement-host-address placement:50006 \
  --resources-path .dapr/resources \
  --scheduler-host-address scheduler:50007
```

The current `DaprSidecarOptions` class supports customizing the placement service's address using the `PlacementHostAddress` property. `DaprSidecarOptions` is currently missing a `SchedulerHostAddress` property to customize the host address for the scheduler service.
