### ISSUE TITLE
BindMount issue roll up

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#7078]
There are several issues with `WithBindMount` that have been filed by users resulting in 2 themes:

1. When there's a mismatch between the container and the host user, the container may have insufficient permissions to access to file.
2. When the host for the docker container isn't the same as the machine calling WithBindMount, paths don't get mapped directly. 

We should look into fixing these issues.

**Comment by dbreshears** [comment]
Moving to the backlog as we need to discuss options and scope is a bit large for 9.1.

**Comment by lvde0** [comment]
I noticed that `WithBindMount()` manually roots the path (via `Path.GetFullPath()`) which causes permission issues in docker compose:

It generates:

```yaml
    volumes:
      - type: "bind"
        target: "/app/cert.crt"
        source: "C:\\Repos\\aspire-test\\certs\\cert.crt"
        read_only: false
```

But the container (`dotnet/nightly/yarp:2.3.0-preview.4`) fails to read it. When I manually tweak the compose file and set `source` as a relative path (`../certs/cert.crt`) it works just fine.

OS: Windows 11

**Comment by RaspeR87** [comment]
> I noticed that `WithBindMount()` manually roots the path (via `Path.GetFullPath()`) which causes permission issues in docker compose:
> 
> It generates:
> 
>     volumes:
>       - type: "bind"
>         target: "/app/cert.crt"
>         source: "C:\\Repos\\aspire-test\\certs\\cert.crt"
>         read_only: false
> But the container (`dotnet/nightly/yarp:2.3.0-preview.4`) fails to read it. When I manually tweak the compose file and set `source` as a relative path (`../certs/cert.crt`) it works just fine.
> 
> OS: Windows 11

Same for me...any workaround?

**Comment by davidfowl** [comment]
What version of aspire are you using @RaspeR87 ?

**Comment by RaspeR87** [comment]
Latest stable, 9.5.1 and same version for CLI.
Do I need to use any preview or daily build instead?

**Comment by davidfowl** [comment]
WithBindMount shouldn't attempt to resolve the path if it's already rooted. Can you share an example?

**Comment by RaspeR87** [comment]
@davidfowl this is example of Aspire orchestration code:

```
var keycloak = builder.AddDockerfile("a02-keycloak", "../../keycloak")
    .WaitFor(keycloak_db)
    .WaitFor(otelCollector)
    .WithLifetime(ContainerLifetime.Persistent)
    .WithContainerRuntimeArgs("--restart", "on-failure:5")
    .WithEnvironment("KC_BOOTSTRAP_ADMIN_USERNAME", Environment.GetEnvironmentVariable("KEYCLOAK_ADMIN"))
    ...
    .WithBindMount("../../keycloak/otel/opentelemetry-javaagent.jar", "/otel/opentelemetry-javaagent.jar")
    .WithBindMount("../../keycloak/providers/keycloak-hsm/target/deploy/keycloak-hsm-provider-1.0.0.jar", "/opt/keycloak/providers/keycloak-hsm-provider-1.0.0.jar", true)
    .WithBindMount("../../keycloak/realms/dev", "/opt/keycloak/data/import", isReadOnly: true)
    ...
    .WithHttpEndpoint(8080, 8080, "http")
    .WithHttpEndpoint(9000, 9000, "management")
    .WithUrlForEndpoint("http", url => { url.DisplayText = "Admin Console (HTTP)"; url.Url += "/"; })
    .WithUrlForEndpoint("management", url => { url.DisplayText = "Management Interface"; url.Url += "/"; })
    .WithArgs("start-dev", "--import-realm", "--features=scripts", "--spi-script-upload-enabled=true")
    .WithExternalHttpEndpoints()
    .WithHttpHealthCheck($"{authHostname(true)}/health/ready");
```

And this is how it is transformed to docker-compose file:

```
...
volumes:
      - type: "bind"
        target: "/otel/opentelemetry-javaagent.jar"
        source: "C:\\Users\\gasperr\\source\\repos\\XYZ\\xzy-root\\infra\\keycloak\\otel\\opentelemetry-javaagent.jar"
        read_only: false
      - type: "bind"
        target: "/opt/keycloak/providers/keycloak-hsm-provider-1.0.0.jar"
        source: "C:\\Users\\gasperr\\source\\repos\\XYZ\\xzy-root\\infra\\keycloak\\providers\\keycloak-hsm\\target\\deploy\\keycloak-hsm-provider-1.0.0.jar"
        read_only: true
      - type: "bind"
        target: "/opt/keycloak/data/import"
        source: "C:\\Users\\gasperr\\source\\repos\\XZY\\xzy-root\\infra\\keycloak\\realms\\dev"
        read_only: true
    depends_on:
....
```

I dont want to have full path, better to have relative in docker compose too
