### ISSUE TITLE
Support WaitForCompletion for ContainerResource resources

### ISSUE THREAD

**Issue by jbogard** [dotnet/aspire#8001]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm converting my Docker Compose configuration to Aspire for my team and one scenario doesn't seem to be supported - using `depends_on` with `service_completed_successfully`. My specific case is [OpenFGA](https://openfga.dev/docs/getting-started/setup-openfga/docker) with the following docker compose YAML:

```yaml
version: '3.8'

networks:
  openfga:

services:
  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - openfga
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    depends_on:
      postgres:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: migrate
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
    networks:
      - openfga

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      - OPENFGA_LOG_FORMAT=json
    command: run
    networks:
      - openfga
    ports:
      # Needed for the http server
      - "8080:8080"
      # Needed for the grpc server (if used)
      - "8081:8081"
      # Needed for the playground (Do not enable in prod!)
      - "3000:3000"
```

The `openfga` container has two commands, `migrate` and `run`, which are mutually exclusive. In the above setup, the `migrate` service runs first (after Postgres is ready). That service runs once to completion, then `openfga` starts up.

I looked at using `WaitForCompletion` but there's two issues here:
- The `migrate` service runs again and again (maybe because Aspire assumes an container exiting is faulted and restarts it?)

This isn't the same as #2866 as I'm not using Azure Container Apps.

### Describe the solution you'd like

First, some sort of "run once" lifetime for container resources, perhaps:

`.WithLifetime(ContainerLifetime.RunOnce)`?

Then the ability to wait for the migrate container to run to completion, something like:

```csharp
var openFgaPgSqlUser = builder.AddParameter("openfga-pgsql-user");
var openFgaPgSqlPassword = builder.AddParameter("openfga-pgsql-password");

var openfga_pgsql = builder.AddPostgres("openfga-postgres", openFgaPgSqlUser, openFgaPgSqlPassword, 5432)
        .WithLifetime(ContainerLifetime.Persistent)
        .WithDataVolume("openfga_postgres_data");

var openfga_migrate = builder.AddContainer("openfga-migrate", "openfga/openfga")
    .WithEnvironment("OPENFGA_DATASTORE_ENGINE", "postgres")
    .WithEnvironment("OPENFGA_DATASTORE_URI",
        $"postgres://{openFgaPgSqlUser.Resource.Value}:{openFgaPgSqlPassword.Resource.Value}@{openfga_pgsql.Resource.Name}:5432/postgres?sslmode=disable")
    .WithArgs("migrate")
    .WaitFor(openfga_pgsql)
    .WithLifetime(ContainerLifetime.RunOnce)
    ;

builder.AddContainer("openfga", "openfga/openfga")
    .WithEndpoint(8080, 8080, name: "http")
    .WithEndpoint(8081, 8081, name: "grpc")
    .WithEndpoint(3000, 3000, name: "noclue")
    .WithEnvironment("OPENFGA_DATASTORE_ENGINE", "postgres")
    .WithEnvironment("OPENFGA_DATASTORE_URI",
        $"postgres://{openFgaPgSqlUser.Resource.Value}:{openFgaPgSqlPassword.Resource.Value}@{openfga_pgsql.Resource.Name}:5432/postgres?sslmode=disable")
    .WithEnvironment("OPENFGA_LOG_FORMAT", "postgres")
    .WithArgs("run")
    .WaitForCompletion(openfga_migrate)
    ;
```
