### ISSUE TITLE
`AddRedis` does not work when using `AddDockerComposePublisher` and publishing.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#8414]
The password variable doesn't get passed through to the container.

**Comment by davidfowl** [comment]
## 🐞 Problem: Docker Compose Interpolates Env Vars in `command`, Breaking Runtime Expansion

When trying to pass a container environment variable (e.g. `REDIS_PASSWORD`) into a `command` string inside `docker-compose.yml`, Compose expands it at **YAML parse time**, not at runtime inside the container. This leads to surprises when the variable ends up blank in the actual command.

### Example of the problem:

```yaml
services:
  cache:
    image: redis:7.4
    command: ["sh", "-c", "redis-server --requirepass $REDIS_PASSWORD"]
    environment:
      REDIS_PASSWORD: "${CACHE_PASSWORD}" # set from host env or .env
```

Even though the `REDIS_PASSWORD` env var is set for the container, the command ends up being:

```sh
redis-server --requirepass 
```

Why? Because **Docker Compose parses `$REDIS_PASSWORD` on the host**, where it's usually not defined — so it becomes an empty string before it even reaches the container.

---

## ✅ Solution: Escape the Dollar Sign with `$$`

To ensure the variable is **evaluated at runtime inside the container**, escape the dollar sign:

```yaml
services:
  cache:
    image: redis:7.4
    command: ["sh", "-c", "redis-server --requirepass $$REDIS_PASSWORD"]
    environment:
      REDIS_PASSWORD: "${CACHE_PASSWORD}"
```

### Why this works:
- `$$` is interpreted by Compose as a literal `$` in the final string.
- `command: ["sh", "-c", "..."]` runs the command in a shell inside the container.
- `$REDIS_PASSWORD` is now expanded by the container’s shell using the environment variable passed via `environment:`.

---

## 🧪 Pro Tip: Debug with `docker compose config`

Run:

```bash
docker compose config
```

This shows you what Docker Compose actually *generated* — if you see `--requirepass ""` you know interpolation happened too early.

---
