### ISSUE TITLE
Docker compose publisher doesn't fill Redis password in default aspire template - unable to run via docker compose up

### ISSUE THREAD

**Issue by Misiu** [dotnet/aspire#9324]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I'm creating a new project using the default template from VS2022, I've updated to Aspire 9.2.1, and added `AddDockerComposePublisher`.

Generated `docker-compose.yaml`:
```
services:
  cache:
    image: "docker.io/library/redis:7.4"
    command:
      - "-c"
      - "redis-server --requirepass $$REDIS_PASSWORD"
    entrypoint:
      - "/bin/sh"
    environment:
      REDIS_PASSWORD: "${CACHE_PASSWORD}"
    ports:
      - "8000:6379"
    networks:
      - "aspire"
  apiservice:
    image: "${APISERVICE_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8001"
    ports:
      - "8002:8001"
      - "8004:8003"
    networks:
      - "aspire"
  webfrontend:
    image: "${WEBFRONTEND_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8005"
      ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
      services__apiservice__http__0: "http://apiservice:8001"
    ports:
      - "8006:8005"
      - "8008:8007"
    depends_on:
      cache:
        condition: "service_started"
      apiservice:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
```

Generated `.env`:
```
# Parameter cache-password
CACHE_PASSWORD=

# Container image name for apiservice
APISERVICE_IMAGE=apiservice:latest

# Container image name for webfrontend
WEBFRONTEND_IMAGE=webfrontend:latest
```

When running `docker compose up` we get this output:
```
Attaching to apiservice-1, cache-1, webfrontend-1
cache-1        |
cache-1        | *** FATAL CONFIG FILE ERROR (Redis 7.4.3) ***
cache-1        | Reading the configuration file, at line 2
cache-1        | >>> 'requirepass'
cache-1        | wrong number of arguments
cache-1 exited with code 1
```

After filling the `CACHE_PASSWORD` in the `.env` file the app started successfully.

The option is to replace:
```
var cache = builder.AddRedis("cache");
```
with:
```
var redisPass = builder.AddParameter("redisPass", "WORKS", true);
var cache = builder.AddRedis("cache", password: redisPass);
```

then the `.env` file is filled correctly.

### Expected Behavior

When publishing a project, the default password for Redis should be provided in .env, or a warning should be displayed when running the command

### Steps To Reproduce

1. Create a new project using .NET Aspire Starter App
2. Update to Aspire 9.2.1
3. Add `Aspire.Hosting.Docker` in version 9.2.1-preview.1.25222.1
4. Add `builder.AddDockerComposePublisher();`
5. Run `aspire publish`
6. Run `docker compose up`
7. Observer error and check generated .env and docker-compose.yaml files

Repo: https://github.com/Misiu/AspireDockerPublisherTest

### .NET Version info

.NET SDK:
 Version:           9.0.300
 Commit:            15606fe0a8
 Workload version:  9.0.300-manifests.af4147de
 MSBuild version:   17.14.5+edd3bbf37

Środowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.300\

### Anything else?

.NET Aspire version: 9.2.1
IDE: VS2022 7.14.0
