### ISSUE TITLE
Add support for AKS

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#9613]
Today we have support for Azure Container Apps and Kubernetes but not provisioning AKS clusters as part of deployment. The goal would be to add AKS support so that we can provision the Kubernetes cluster, setup workload identity so that managed identity works and then being able to express that reference to the right user assigned id in the k8s deployment so that accessing azure resources works seamlessly.

## Example

Below is a **single, minimal Bicep file** that wires up:

* An AKS cluster with **OIDC issuer** + **Workload Identity** turned on
* A **user-assigned managed identity** (UAMI)
* A **federated-identity credential** that trusts a single Kubernetes service-account (`blob-sa` in the `default` namespace)
* A **StorageV2 account**
* A **role assignment** so the UAMI gets **Storage Blob Data Contributor** on that storage account

```bicep
@description('Azure region for all resources')
param location string = resourceGroup().location

@description('Friendly name for the AKS cluster')
param aksName string = 'aks-wi-demo'

@description('Kubernetes namespace that will host the service account')
param k8sNamespace string = 'default'

@description('ServiceAccount name that your pod will use')
param k8sServiceAccount string = 'blob-sa'

@description('Name for the user-assigned managed identity')
param uamiName string = 'blob-uami'

@description('Globally-unique storage account name (3-24 lowercase letters & numbers)')
@minLength(3)
@maxLength(24)
param storageName string = toLower(uniqueString(resourceGroup().id, 'storage'))

// -------------------------  MANAGED IDENTITY  -------------------------
resource uami 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: uamiName
  location: location
}

// -------------------------  STORAGE ACCOUNT  --------------------------
resource storage 'Microsoft.Storage/storageAccounts@2023-01-01' = {
  name: storageName
  location: location
  kind: 'StorageV2'
  sku: {
    name: 'Standard_LRS'
  }
  properties: {
    allowBlobPublicAccess: false
    minimumTlsVersion: 'TLS1_2'
  }
}

// Grant the UAMI permission to the storage account (roleId = Storage Blob Data Contributor)
resource blobContributor 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(storage.id, uami.properties.principalId, 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')
  scope: storage
  properties: {
    roleDefinitionId: subscriptionResourceId(
      'Microsoft.Authorization/roleDefinitions',
      'ba92f5b4-2d11-453d-a403-e96b0029c9fe'   // Storage Blob Data Contributor
    )
    principalId: uami.properties.principalId
  }
}

// -------------------------  AKS CLUSTER  ------------------------------
resource aks 'Microsoft.ContainerService/managedClusters@2023-05-01' = {
  name: aksName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  sku: {
    name: 'Basic'
    tier: 'Paid'
  }
  properties: {
    dnsPrefix: '${aksName}-dns'
    kubernetesVersion: ''
    agentPoolProfiles: [
      {
        name: 'system'
        vmSize: 'Standard_DS2_v2'
        count: 1
        osType: 'Linux'
        mode: 'System'
      }
    ]

    // --- Workload Identity & OIDC issuer ---
    oidcIssuerProfile: {
      enabled: true
    }
    workloadIdentityProfile: {
      enabled: true
    }
  }
}

// ------------------  FEDERATED-IDENTITY CREDENTIAL  -------------------
/*
   This child resource “binds” the UAMI to one ServiceAccount.
   The issuer URL comes from the cluster you just created.
   If the deployment engine complains that the value isn’t available
   yet, split the template in two steps—first AKS, then this block.
*/
resource fic 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2023-01-31' = {
  name: 'fic-${k8sServiceAccount}'
  parent: uami
  dependsOn: [
    aks   // make sure AKS exists so issuerUrl is populated
  ]
  properties: {
    issuer: aks.properties.oidcIssuerProfile.issuerUrl
    subject: 'system:serviceaccount:${k8sNamespace}:${k8sServiceAccount}'
    audiences: [
      // This is the constant expected by Azure’s token-exchange endpoint
      'api://AzureADTokenExchange'
    ]
  }
}

// -------------------------  OUTPUTS  ----------------------------------
output storageEndpoint string = storage.properties.primaryEndpoints.blob
output uamiClientId string = uami.properties.clientId
output aksOidcIssuer string = aks.properties.oidcIssuerProfile.issuerUrl
```

### How it hangs together — quick notes

| Block                                                               | Why it matters                                                                                                                                                                                 |
| ------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **`oidcIssuerProfile.enabled` & `workloadIdentityProfile.enabled`** | Turns on the OIDC endpoint and Microsoft Entra **Workload ID** feature for the whole cluster. ([Microsoft Learn][1])                                                                           |
| **Federated-identity credential** (`fic`)                           | Tells Entra ID “if I get a token whose issuer is **this cluster’s OIDC URL** and whose subject is **system\:serviceaccount\:default\:blob-sa**, treat it as the managed identity’s own token.” |
| **Role assignment**                                                 | Gives that identity *Storage Blob Data Contributor* on the storage account so the exchanged access token is actually authorized.                                                               |
| **Outputs**                                                         | Handy values you’ll feed into your Helm charts or `kubectl` manifests: `AZURE_CLIENT_ID`, storage account name, and OIDC issuer if you need it elsewhere.                                      |

> **Deploy order tip**
> AKS only surfaces the `issuerUrl` after the control-plane reaches a *Succeeded* state. In 99 % of cases, referencing it inside the same template works fine. If you hit the rare timing race, deploy the template twice (or split it): first creates AKS, second wires up `fic` and the role binding.

Once this template is applied, the pod manifest you created earlier will authenticate seamlessly with `DefaultAzureCredential`—no connection strings, no keys, no extra secrets.

[1]: https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster?utm_source=chatgpt.com "Deploy and configure an AKS cluster with workload identity"

## The Kubernetes side

Below is a **single-file manifest** you can `kubectl apply -f` after the Bicep deployment finishes.
Replace the three place-holders with the values that came back from the Bicep outputs (or wire them in with Helm/Kustomize).

```yaml
# k8s/blob-identity.yaml
# -------------------------------------------------
# 1. ServiceAccount bound to the user-assigned managed identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blob-sa
  namespace: default
  annotations:
    # <<< paste the UAMI client-id from the Bicep output uamiClientId >>>
    azure.workload.identity/client-id: "<UAMI_CLIENT_ID>"

---
# 2. Workload that reads/writes Azure Blob Storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-demo
  template:
    metadata:
      labels:
        app: blob-demo
      annotations:
        # Opt-in to Microsoft Entra Workload ID token injection
        azure.workload.identity/use: "true"
    spec:
      # Bind the pod to the ServiceAccount above
      serviceAccountName: blob-sa

      containers:
      - name: api
        # Any image that uses the Azure SDK works; this is just an example
        image: mcr.microsoft.com/dotnet/samples:aspnetapp

        # ---- Environment the Azure SDK needs ----
        env:
        # 2.1 Tell the SDK which managed identity to use
        - name: AZURE_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['azure.workload.identity/client-id']

        # 2.2 Storage-account details your code will reference
        - name: AZURE_STORAGE_ACCOUNT_NAME
          value: "<STORAGE_ACCOUNT_NAME>"     # ← from Bicep output storageName
        - name: AZURE_BLOB_CONTAINER
          value: "images"                    # ← any container you wish

        ports:
        - containerPort: 8080
```

### What happens at runtime

1. The **admission webhook** sees `azure.workload.identity/use: "true"` and:

   * mounts a projected token volume at
     `/var/run/secrets/tokens/azure-identity-token`
   * sets two extra env-vars for you:
     `AZURE_TENANT_ID` and `AZURE_FEDERATED_TOKEN_FILE`
2. The Azure SDK in the container picks up `AZURE_CLIENT_ID` and the token file via `DefaultAzureCredential`.
3. Microsoft Entra exchanges that OIDC token for an **access-token on the managed identity**.
4. Because the identity already has **Storage Blob Data Contributor** on the storage account, all Blob SDK calls succeed—no keys or connection strings required.

That’s all the wiring you need: one ServiceAccount, one annotation, and the usual env-vars your application already expects.
