### ISSUE TITLE
Docker Compose publisher

### ISSUE THREAD

**Issue by MarioGK** [dotnet/aspire#9744]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It would be great if we could configure the docker service source if it is an "image" or a "build".

### Describe the solution you'd like

So instead of:
```yaml
  webapp:
    image: "${WEBAPP_IMAGE}"
```
We would have:
```yaml
  webapp:
    build:
      context: .
      dockerfile: ./WebApp//Dockerfile
```
In the final docker-compose.yaml, this would facilitate having deployment per PR for example or just do a quick and dirty test on another environment.

This would enable easy deploy in Dokploy, Coolify and similar easy self hosted services.
